[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/admin.html"
  function = "admin-basic-auth"

[dev]
  publish = "."
  port = 8888
